import { motion } from "framer-motion";
import { Link } from "react-router-dom";
import {
  Leaf,
  BarChart3,
  Globe,
  ShieldCheck,
  Zap,
  ArrowRight,
  Droplets,
  Wind,
  ShoppingBag,
  Sparkles,
  TrendingDown,
  Activity,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { Layout } from "@/components/Layout";

const fadeInUp = {
  initial: { opacity: 0, y: 30 },
  animate: { opacity: 1, y: 0 },
  transition: { duration: 0.6 },
};

const stagger = {
  animate: { transition: { staggerChildren: 0.1 } },
};

const features = [
  {
    icon: BarChart3,
    title: "Real Time Dashboard",
    desc: "Track electricity, CO₂, water, and air pollutant impact of your AI usage with interactive charts and breakdowns.",
    color: "from-pt-emerald to-pt-teal",
  },
  {
    icon: Globe,
    title: "Geo Specific Modeling",
    desc: "Region aware calculations using local grid intensity data for 13+ regions. Your location changes everything.",
    color: "from-pt-blue to-pt-violet",
  },
  {
    icon: TrendingDown,
    title: "What If Simulator",
    desc: "Drag sliders to model reduction scenarios and see instant recalculations. Compare regions, habits, and targets.",
    color: "from-pt-violet to-pt-rose",
  },
  {
    icon: ShoppingBag,
    title: "Carbon Offset Store",
    desc: "Purchase verified carbon credits to offset your computed emissions with full transparency and detailed receipts.",
    color: "from-pt-amber to-pt-rose",
  },
  {
    icon: Activity,
    title: "Multi Source Data",
    desc: "Connect via manual entry, iOS Shortcuts, Android Digital Wellbeing exports, or browser extension for automatic tracking.",
    color: "from-pt-cyan to-pt-blue",
  },
  {
    icon: ShieldCheck,
    title: "Privacy First",
    desc: "Your data stays yours. Minimal storage, transparent methodology, and full data deletion capability built in.",
    color: "from-pt-lime to-pt-emerald",
  },
];

const stats = [
  { value: "13+", label: "Regions", icon: Globe },
  { value: "5", label: "AI Categories", icon: Sparkles },
  { value: "±35%", label: "Uncertainty Range", icon: Activity },
  { value: "100%", label: "Deterministic", icon: Zap },
];

export default function LandingPage() {
  return (
    <Layout>
      {/* Hero */}
      <section className="relative overflow-hidden gradient-hero">
        {/* Decorative blobs */}
        <div className="absolute top-20 left-10 w-72 h-72 rounded-full bg-pt-emerald/10 blur-3xl animate-pulse-glow" />
        <div className="absolute bottom-20 right-10 w-96 h-96 rounded-full bg-pt-violet/10 blur-3xl animate-pulse-glow" style={{ animationDelay: "1.5s" }} />
        <div className="absolute top-40 right-1/3 w-48 h-48 rounded-full bg-pt-blue/10 blur-3xl animate-pulse-glow" style={{ animationDelay: "3s" }} />

        <div className="container relative py-24 md:py-36">
          <motion.div
            className="max-w-3xl mx-auto text-center space-y-8"
            initial="initial"
            animate="animate"
            variants={stagger}
          >
            <motion.div variants={fadeInUp}>
              <span className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full glass text-sm font-medium text-primary">
                <Leaf className="h-4 w-4" />
                Environmental Impact Dashboard for AI
              </span>
            </motion.div>

            <motion.h1
              variants={fadeInUp}
              className="font-display text-5xl md:text-7xl font-bold tracking-tight text-balance leading-[1.1]"
            >
              Know the{" "}
              <span className="gradient-text-primary">true cost</span> of every prompt
            </motion.h1>

            <motion.p
              variants={fadeInUp}
              className="text-lg md:text-xl text-muted-foreground max-w-2xl mx-auto text-balance"
            >
              PromptTax reveals the electricity, carbon emissions, water usage, and air pollutants
              generated by your AI tools. Understand your impact, reduce it, and offset the rest.
            </motion.p>

            <motion.div variants={fadeInUp} className="flex flex-wrap justify-center gap-4">
              <Button
                size="lg"
                className="gradient-primary text-white border-0 px-8 h-12 text-base font-semibold shadow-lg hover:shadow-xl transition-shadow"
                asChild
              >
                <Link to="/connect">
                  Start Tracking
                  <ArrowRight className="ml-2 h-4 w-4" />
                </Link>
              </Button>
              <Button
                size="lg"
                variant="outline"
                className="h-12 px-8 text-base glass"
                asChild
              >
                <Link to="/dashboard">View Demo Dashboard</Link>
              </Button>
            </motion.div>

            {/* Mini stats */}
            <motion.div
              variants={fadeInUp}
              className="flex flex-wrap justify-center gap-6 pt-8"
            >
              {stats.map((stat) => (
                <div
                  key={stat.label}
                  className="flex items-center gap-2 px-4 py-2 rounded-xl glass-subtle"
                >
                  <stat.icon className="h-4 w-4 text-primary" />
                  <span className="font-display font-bold text-lg">{stat.value}</span>
                  <span className="text-sm text-muted-foreground">{stat.label}</span>
                </div>
              ))}
            </motion.div>
          </motion.div>
        </div>
      </section>

      {/* Impact preview cards */}
      <section className="py-20 bg-background">
        <div className="container">
          <motion.div
            className="text-center space-y-4 mb-16"
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
          >
            <h2 className="font-display text-3xl md:text-4xl font-bold">
              What your AI usage really costs
            </h2>
            <p className="text-muted-foreground max-w-xl mx-auto">
              Every prompt, search, and generated image has an environmental footprint. Here is what a typical day looks like.
            </p>
          </motion.div>

          <motion.div
            className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6"
            initial="initial"
            whileInView="animate"
            viewport={{ once: true }}
            variants={stagger}
          >
            {[
              { icon: Zap, label: "Electricity", value: "0.42 kWh", sub: "Like running a LED bulb for 4 hours", color: "text-pt-amber" },
              { icon: Wind, label: "CO₂ Emissions", value: "164g", sub: "Equivalent to driving 0.6 km", color: "text-pt-rose" },
              { icon: Droplets, label: "Water Usage", value: "0.92 L", sub: "Nearly a full glass of water", color: "text-pt-blue" },
              { icon: Leaf, label: "Air Pollutants", value: "7.6 mg", sub: "PM2.5 particulate matter", color: "text-pt-emerald" },
            ].map((card) => (
              <motion.div
                key={card.label}
                variants={fadeInUp}
                className="group relative p-6 rounded-2xl glass hover:shadow-lg transition-all duration-300 hover:-translate-y-1"
              >
                <div className={`${card.color} mb-4`}>
                  <card.icon className="h-8 w-8" />
                </div>
                <p className="text-sm font-medium text-muted-foreground mb-1">{card.label}</p>
                <p className="font-display text-3xl font-bold mb-2">{card.value}</p>
                <p className="text-xs text-muted-foreground">{card.sub}</p>
              </motion.div>
            ))}
          </motion.div>
        </div>
      </section>

      {/* Features grid */}
      <section className="py-20 gradient-hero">
        <div className="container">
          <motion.div
            className="text-center space-y-4 mb-16"
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
          >
            <h2 className="font-display text-3xl md:text-4xl font-bold">
              Everything you need to understand and act
            </h2>
            <p className="text-muted-foreground max-w-xl mx-auto">
              From data collection to carbon offsetting, PromptTax provides the complete toolkit.
            </p>
          </motion.div>

          <motion.div
            className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6"
            initial="initial"
            whileInView="animate"
            viewport={{ once: true }}
            variants={stagger}
          >
            {features.map((feature) => (
              <motion.div
                key={feature.title}
                variants={fadeInUp}
                className="group relative p-6 rounded-2xl glass hover:shadow-lg transition-all duration-300"
              >
                <div
                  className={`inline-flex h-12 w-12 items-center justify-center rounded-xl bg-gradient-to-br ${feature.color} mb-4`}
                >
                  <feature.icon className="h-6 w-6 text-white" />
                </div>
                <h3 className="font-display text-lg font-semibold mb-2">{feature.title}</h3>
                <p className="text-sm text-muted-foreground leading-relaxed">{feature.desc}</p>
              </motion.div>
            ))}
          </motion.div>
        </div>
      </section>

      {/* CTA */}
      <section className="py-24 bg-background">
        <div className="container">
          <motion.div
            className="max-w-2xl mx-auto text-center space-y-6 p-12 rounded-3xl glass"
            initial={{ opacity: 0, scale: 0.95 }}
            whileInView={{ opacity: 1, scale: 1 }}
            viewport={{ once: true }}
          >
            <div className="inline-flex h-16 w-16 items-center justify-center rounded-2xl gradient-primary mx-auto">
              <Leaf className="h-8 w-8 text-white" />
            </div>
            <h2 className="font-display text-3xl font-bold">Ready to know your impact?</h2>
            <p className="text-muted-foreground">
              Start tracking in under 2 minutes. No account required to explore the demo dashboard.
            </p>
            <div className="flex flex-wrap justify-center gap-4">
              <Button
                size="lg"
                className="gradient-primary text-white border-0 px-8 h-12 text-base font-semibold"
                asChild
              >
                <Link to="/connect">
                  Connect Your Data
                  <ArrowRight className="ml-2 h-4 w-4" />
                </Link>
              </Button>
              <Button size="lg" variant="outline" className="h-12 px-8 text-base" asChild>
                <Link to="/methodology">Read the Methodology</Link>
              </Button>
            </div>
          </motion.div>
        </div>
      </section>
    </Layout>
  );
}
